### ISSUE TITLE
DaysAvailable functionality is not implemented

### ISSUE THREAD

**Issue by adamkr13** [adamkr13/Boats-4-U#12]
I could use properties of bool for each day or I could try to make a new class that would have a list similar to the way ratings were done for Restaurant Rater.

**Comment by caddie89** [comment]
Able to create a "DaysOfWeek" enum and decorate it with the [Flags] attribute. In order to do this, labels have to be manually initialized as powers of two. Attached are some articles/StackOverflows that were useful in coming up with this work around. 

**Enum, Flags, and Bitwise Operators**
[https://www.alanzucconi.com/2015/07/26/enum-flags-and-bitwise-operators/](url)

**C# Json.NET Render Flags Enum as String Array**
[https://stackoverflow.com/questions/43143175/c-sharp-json-net-render-flags-enum-as-string-array](url)

**How do you pass multiple enum values in C#?**
[https://stackoverflow.com/questions/1030090/how-do-you-pass-multiple-enum-values-in-c](url)
